version: '3'

services:
  app:
    build: ./app
    ports:
      - "8081:3000"
    volumes:
      - ./app:/usr/src/app/app
  api:
    restart: always
    build: ./api
    ports:
      - '80:3000'
    links:
      - mongo
    volumes:
      - ./api:/usr/src/app/api
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'