version: '3'

services:
  app:
    build: ./app
    ports:
      - "8081:3000"
    volumes:
      - ./app:/usr/src/app/app
  api:
    restart: always
    build: ./api
    ports:
      - '80:3000'
    links:
      - mongo
      - crawler
    volumes:
      - ./api:/usr/src/app/api
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./mongo:/data/db
  crawler:
    restart: always
    build: ./crawler
    ports: 
      - '8082:8082'
    volumes:
      - ./crawler:/usr/src/app/crawler