version: '3'

services:
  # app:
  #   container_name: app
  #   build: ./app
  #   ports:
  #     - "8081:3000"
  #     - "3000:3000"
  #   links:
  #     - api
  #   volumes:
  #     - ./app:/usr/src/app/app
  nuxt:
    container_name: nuxt
    build: ./nuxt
    ports:
      - "8083:8083"
      - "3000:3000"
    links:
      - api
    volumes:
      - ./nuxt:/usr/src/app/nuxt
    networks:
      - app
  api:
    container_name: api
    restart: always
    build: ./api
    ports:
      - '80:3000'
    links:
      - mongo
      - crawler
    volumes:
      - ./api:/usr/src/app/api
    networks:
      - app
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./mongo:/data/db
    networks:
      - app
  crawler:
    restart: always
    build: ./crawler
    ports: 
      - '8082:8082'
    volumes:
      - ./crawler:/usr/src/app/crawler
    networks:
      - app

networks:
  app:
    driver: bridge