query GET_PRODUCT($code: String, $page: Int, $day: Int, $ProductFilter: ProductFilter) {
	product (code: $code, page: $page, day: $day, filter: $ProductFilter){
    _id
    code
    title
    image
    sale
    categories {
      _id
      title
      code
      url
      products {
        code
        title
        image
        sale
        records {
          date
          prices {
            amount
            value
          }
        }
      }
    }
    brands {
      _id
      title
      code
      url
      products {
        code
        title
        image
        sale
        records {
          date
          prices {
            amount
            value
          }
        }
      }
    }
    records {
      date
      prices {
        amount
        value
      }
    }
  }
}

query PREVIEW_PRODUCT($code: String, $url: String) {
  previewProduct (code: $code, url: $url) {
    code
    title
    image
    prices {
      amount
      value
    }
  }
}

mutation ADD_PRODUCT($code: String) {
  addProduct (code: $code) {
    title
    code
  }
}